redirects:
  "/ways-to-train-guidance": "/guidance/train-to-become-a-teacher"
  "/train-to-become-a-teacher": "/guidance/train-to-become-a-teacher"

  "/finance-guidance": "/guidance/financial-support-for-teacher-training"
  "/financial-support-for-teacher-training": "/guidance/financial-support-for-teacher-training"

  "/guidance": "guidance/become-a-teacher-in-england"
