name: Build and Deploy
on:
  repository_dispatch:
  push:
    branches:
      - master
env:
  DOCKERHUB_REPOSITORY: dfedigital/get-into-teaching-frontend
  GOVUKPAAS_ORG: dfe-teacher-services
  GOVUKPAAS_SPACE: get-into-teaching
  CONTAINER: get-into-teaching-app
jobs:
  build_and_push:
    name: Build and push to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build and push to DockerHub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PERSONAL_ACCESS_TOKEN }}
          repository: ${{ env.DOCKERHUB_REPOSITORY }}
          always_pull: true
          add_git_labels: true
          tag_with_ref: true
          tag_with_sha: true
          push: true
  deploy:
    name: Deploy to sandbox GovUK PaaS
    runs-on: ubuntu-latest
    needs:
      - build_and_push
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Download CloudFoundry CLI
        run: wget -O /tmp/cf-cli.deb "https://packages.cloudfoundry.org/stable?release=debian64&source=github"
      - name: Install CloudFoundry CLI
        run: sudo dpkg -i /tmp/cf-cli.deb
      - name: Get Short SHA
        id: sha
        run: echo ::set-output name=short::$(git rev-parse --short $GITHUB_SHA)
      - name: Deploy Built Image
        uses: cuchi/jinja2-action@v1.1.0
        with:
          template:  manifest.yml.j2
          output_file:  manifest.yml
          variables: |
              HTTPAUTH_PASSWORD="${{ secrets.HTTPAUTH_PASSWORD }}"
              HTTPAUTH_USERNAME="${{ secrets.HTTPAUTH_USERNAME }}"
              RAILS_MASTER_KEY="${{ secrets.RAILS_MASTER_KEY_ROLLING }}"
              RAILS_ENV="rolling"
              APPLICATION="${{env.CONTAINER}}"
              DOCKER_IMAGE=${{env.DOCKERHUB_REPOSITORY}}:sha-${{ steps.sha.outputs.short}}
      - name: Login to PaaS
        run: cf login -a api.london.cloud.service.gov.uk -u "${{ secrets.GOVUKPAAS_USERNAME }}" -p "${{ secrets.GOVUKPAAS_PASSWORD }}" -o $GOVUKPAAS_ORG -s $GOVUKPAAS_SPACE
      - name: Push Manifest
        run: cf push 
