---  
name: Release to test
on: 
   release:
     types:  [edited, created]
env:
  DOCKERHUB_REPOSITORY: dfedigital/get-into-teaching-frontend
  TF_VAR_user:              "${{ secrets.GOVUKPAAS_USERNAME  }}"
  TF_VAR_password:          "${{ secrets.GOVUKPAAS_PASSWORD  }}"
  TF_VAR_HTTPAUTH_PASSWORD: "${{ secrets.HTTPAUTH_PASSWORD }}"
  TF_VAR_HTTPAUTH_USERNAME: "${{ secrets.HTTPAUTH_USERNAME }}"
  TF_VAR_RAILS_MASTER_KEY:  "${{ secrets.RAILS_MASTER_KEY_PREPROD }}"
  TF_VAR_RAILS_ENV:         "preprod"
  ARM_ACCESS_KEY:           "${{ secrets.TEST_ARM_ACCESS_KEY  }}"
  CF_PROVIDER_DIR: $HOME/.terraform.d/plugins/linux_amd64/terraform-provider-cloudfoundry

jobs:
  deploy_qa:
    name: 'Deploy to Quality Assurance'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
       - name: Checkout
         uses: actions/checkout@v2

       - name: Get Short SHA
         id: sha
         run: echo ::set-output name=short::$(git rev-parse --short $GITHUB_SHA)

       - name: Get parent SHA 
         run: |
           echo ::set-env name=parent_sha::$(docker run dfedigital/get-into-teaching-web:latest cat /etc/get-into-teaching-app-sha)

       - name: Set new docker image version
         run: |
           docker_image_tag="sha-${{ steps.sha.outputs.short }}-${parent_sha}"
           echo ::set-env name=docker_image_tag::${docker_image_tag}
           echo "Content SHA: ${{ steps.sha.outputs.short }}"
           echo "Parent SHA: ${parent_sha}"
           echo "New version tag: ${docker_image_tag}"

       - name: Install Terraform CloudFoundry Provider
         run: |
             mkdir -p $HOME/.terraform.d/plugins/linux_amd64
             wget -O ${{ env.CF_PROVIDER_DIR }} https://github.com/cloudfoundry-community/terraform-provider-cf/releases/latest/download/terraform-provider-cloudfoundry_linux_amd64
             chmod +x ${{ env.CF_PROVIDER_DIR }}
   
       - name: Terraform Init
         run: |
             cd terraform/paas && pwd
             terraform init -backend-config=test.bk.vars

       - name: Terraform Plan
         run: |
             cd terraform/paas && pwd
             terraform plan -var-file=test.env.tfvars -out plan
         env:
             TF_VAR_paas_app_docker_image: ${{env.DOCKERHUB_REPOSITORY}}:${{ env.docker_image_tag }}

       - name: Terraform Apply
         run: |
             cd terraform/paas && pwd
             terraform apply -auto-approve plan
