---  
name: Siege Testing
on: 
  workflow_dispatch:
jobs:
  siege:
    name: Put Server under siege
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:

       - name: Run Tests
         run: |
            auth=$(echo -n '${{secrets.HTTPAUTH_USERNAME}}:${{secrets.HTTPAUTH_PASSWORD}}' | openssl base64)
            docker run --rm -t yokogawa/siege --header="Authorization:Basic $auth" -t60s -d10 -c20 https://get-into-teaching-app-dev.london.cloudapps.digital
