---  
name: Siege Testing
on: 
  workflow_dispatch:
    inputs:
      concurrency:
        description: 'Concurrency'     
        required: true
        default: '20'
      environment:
        description: 'Environment dev|test'     
        required: true
        default: 'dev'
jobs:
  siege:
    name: Put Server under siege
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:

       - name: Run Tests
         run: |
            mkdir out
            chmod a=rwx out
            auth=$(echo -n '${{secrets.HTTPAUTH_USERNAME}}:${{secrets.HTTPAUTH_PASSWORD}}' | openssl base64)
            echo "AUTHENTICATE TO ${auth}"
            docker run --rm -v $(PWD)/out:/var/log/ -t yokogawa/siege \
                                   --header='Authorization:Basic $auth' -t60s -d10 -c'${{ github.event.inputs.concurrency}}' \
                                   'https://get-into-teaching-app-${{github.event.inputs.environment}}.london.cloudapps.digital'

       - uses: actions/upload-artifact@v2
         with:
           name: siege.log 
           path: out/siege.log
