name: Update base image
on:
  repository_dispatch:

env:
  BASE_IMAGE: dfedigital/get-into-teaching-web

jobs:
  updatebase:
    name: Update base docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Get parent SHA if triggered from app pipeline
        id: parent-sha
        run: |
          echo ::set-output name=full::${{ github.event.client_payload.parent_sha }}
          echo ::set-output name=short::$(${{ github.event.client_payload.parent_sha }} | cut -c -7)

      - name: Derive base image
        id: docker-image
        run: |-
          echo ::set-output name=image::${{ env.BASE_IMAGE }}:sha-${{ steps.parent-sha.outputs.short }}

      - name: New base image
        run: |-
          echo "DOCKER IMAGE: '${{ steps.docker-image.outputs.image }}'"

      - name: Update Dockerfile
        run: |-
          sed -i "s~FROM .*~FROM ${{ steps.docker-image.outputs.image }}~" Dockerfile

      - name: Commit
        run: |
          git config user.name "GiT Workflow Bot"
          git config user.email "<>"
          git add Dockerfile
          git commit -m "Updated base image to sha-${{ steps.parent-sha.outputs.short }}

          ${{ steps.docker-image.outputs.image }}"

      - name: Commit info
        run: git show HEAD

      - name: Push to master
        run: git push origin master
